spring:
  application:
    name: servicesense-api

  datasource:
    url: jdbc:postgresql://localhost:5432/servicesense
    username: dev
    password: dev123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  redis:
    host: localhost
    port: 6379

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-4
        temperature: 0.7

jwt:
  secret: ${JWT_SECRET}
    
server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
